name: Build GitHub Desktop PKG

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download GitHub Desktop
        run: |
          echo "Downloading GitHub Desktop ARM64 version..."
          curl -L -o ~/Desktop/GitHubDesktop.zip "https://desktop.githubusercontent.com/releases/3.4.13-c968496f/GitHubDesktop-arm64.zip"
          echo "Download completed successfully"

      - name: Unzip GitHub Desktop
        run: |
          echo "Unzipping GitHub Desktop to Desktop..."
          cd ~/Desktop
          unzip GitHubDesktop.zip
          echo "Unzip completed successfully"

      - name: Get App Name
        run: |
          echo "Finding extracted application name..."
          cd ~/Desktop
          FileName=$(ls | grep '\.app$' | sed 's/\.app$//')
          echo "Found application: $FileName"
          echo "FILENAME=$FileName" >> $GITHUB_ENV

      - name: Build PKG
        run: |
          echo "Building PKG file for ${{ env.FILENAME }}..."
          pkgbuild --install-location /Applications --component ~/Desktop/${{ env.FILENAME }}.app ~/Desktop/${{ env.FILENAME }}.pkg
          echo "PKG build completed successfully"

      - name: Upload to Azure Blob Storage with SAS
        run: |
          echo "Uploading PKG to Azure Blob Storage..."
          curl -X PUT -H "x-ms-blob-type: BlockBlob" \
            -T ~/Desktop/${{ env.FILENAME }}.pkg \
            "${{ secrets.BLOB_SAS_URL }}/${{ env.FILENAME }}.pkg${{ secrets.BLOB_SAS_TOKEN }}"
          echo "Upload to Azure Blob Storage completed successfully"
