name: Build VS Code PKG

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download VS Code
        run: |
          echo "Downloading VS Code ARM64 version..."
          curl -L -o ~/Desktop/VSCode.zip "https://update.code.visualstudio.com/1.96.4/darwin-arm64/stable"
          echo "Download completed successfully"

      - name: Unzip VS Code
        run: |
          echo "Unzipping VS Code to Desktop..."
          cd ~/Desktop
          unzip VSCode.zip
          echo "Unzip completed successfully"

      - name: Get App Name
        run: |
          echo "Finding extracted application name..."
          cd ~/Desktop
          FileName=$(ls | grep '\.app$' | sed 's/\.app$//')
          echo "Found application: $FileName"
          echo "FILENAME=$FileName" >> $GITHUB_ENV

      - name: Build PKG
        run: |
          echo "Building PKG file for ${{ env.FILENAME }}..."
          pkgbuild --install-location /Applications --component "$HOME/Desktop/${{ env.FILENAME }}.app" "$HOME/Desktop/${{ env.FILENAME }}.pkg"
          echo "PKG build completed successfully"

      - name: Upload to Azure Blob Storage
        env:
          AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
        run: |
          echo "Installing Azure CLI..."
          brew install azure-cli
          echo "Uploading PKG to Azure Blob Storage..."
          az storage blob upload \
            --container-name pkg \
            --file "$HOME/Desktop/${{ env.FILENAME }}.pkg" \
            --name "${{ env.FILENAME }}.pkg" \
            --overwrite true
          echo "Upload to Azure Blob Storage completed successfully"
